### ISSUE TITLE
Getting SyntaxError: invalid syntax on Kin 2.0.2 with Python 2.7.18

### ISSUE THREAD

**Issue by thandang** [Serchinastico/Kin#79]
> `Traceback (most recent call last):
  File "/usr/local/bin/kin", line 11, in <module>
    load_entry_point('kin==2.0.2', 'console_scripts', 'kin')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/kin-2.0.2-py2.7.egg/kin/kin.py", line 5, in <module>
    from .verifier import Verifier
  File "/Library/Python/2.7/site-packages/kin-2.0.2-py2.7.egg/kin/verifier.py", line 1, in <module>
    from antlr4 import *
  File "build/bdist.macosx-11.5-x86_64/egg/antlr4/__init__.py", line 1, in <module>
  File "/Library/Python/2.7/site-packages/antlr4_python3_runtime-4.9.2-py2.7.egg/antlr4/Token.py", line 60
    def text(self, text:str):
                       ^
SyntaxError: invalid syntax`

**Comment by Marlunes** [comment]
Any solution to this one?

**Comment by intspt** [comment]
same question

**Comment by Serchinastico** [comment]
We migrated to Python 3 in Kin 2.0.0 so you should be installing kin with `pip3 install kin` instead.
